---
repos:
  - repo: https://github.com/geek-kb/python_copilot_docs_hook
    rev: v0.1.22
    hooks:
      - id: python-copilot-docs
        additional_dependencies: ["openai>=1.0.0"]
        args:
          - "--openai-key"
          - "${OPENAI_API_KEY}"
          - "--rate-limit"
          - "20"
          - "--rate-period"
          - "60"
