---
repos:
  - repo: https://github.com/geek-kb/python_copilot_docs_hook
    rev: v0.1.11
    hooks:
      - id: python-copilot-docs
        types: [python]
        additional_dependencies: ["openai>=1.0.0"]
        language: python
